# Generated by Django 4.0 on 2021-12-13 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='res_table',
            name='creation_date',
        ),
        migrations.RemoveField(
            model_name='res_table',
            name='update_date',
        ),
    ]
