# Generated by Django 4.0 on 2022-01-23 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='name',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='type_data',
        ),
    ]
