# Generated by Django 4.0 on 2021-12-13 21:10

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0002_remove_res_table_creation_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='res_table',
            name='mpoly',
            field=django.contrib.gis.db.models.fields.MultiPolygonField(blank=True, null=True, srid=3857),
        ),
    ]
