# Generated by Django 4.0 on 2021-12-31 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0002_rename_lesnichestvo_feature_les_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='les',
            new_name='les_name',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='uch_les',
            new_name='uch_les_name',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='uroch',
            new_name='uroch_name',
        ),
    ]
