# Generated by Django 4.0 on 2022-01-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0003_rename_les_feature_les_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='preferences',
        ),
    ]
