# Generated by Django 4.0 on 2021-12-17 09:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0003_layer_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(default='MULTIPOLYGON EMPTY', srid=4326),
        ),
    ]
