# Generated by Django 4.0 on 2021-12-17 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0004_alter_feature_geom'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
