# Generated by Django 4.0 on 2022-01-07 01:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0004_remove_feature_preferences'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='kvartal',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='name',
        ),
    ]
