# Generated by Django 4.0 on 2021-12-15 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0004_mypolygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPolygon',
        ),
    ]
