# Generated by Django 4.0 on 2022-01-31 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0005_alter_feature_jsonb_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minzoom', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('maxzoom', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('layer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='styles', to='geores.layer')),
            ],
            options={
                'ordering': ('id',),
            },
        ),
    ]
