# Generated by Django 4.0 on 2022-01-07 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0005_remove_feature_kvartal_remove_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
