# Generated by Django 4.0 on 2021-12-16 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0006_mypolygon'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyPolygon',
        ),
    ]
