# Generated by Django 4.0 on 2022-03-21 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0006_style'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='style',
            name='maxzoom',
        ),
        migrations.RemoveField(
            model_name='style',
            name='minzoom',
        ),
        migrations.AddField(
            model_name='style',
            name='maxResolution',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='minResolution',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=10, null=True),
        ),
    ]
