# Generated by Django 4.0 on 2022-01-08 15:58

import django.contrib.postgres.fields.hstore
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0007_feature_type_les'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='hstore_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, null=True),
        ),
    ]
