# Generated by Django 4.0 on 2022-03-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0007_remove_style_maxzoom_remove_style_minzoom_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='maxResolution',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
        migrations.AlterField(
            model_name='style',
            name='minResolution',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=100, null=True),
        ),
    ]
