# Generated by Django 4.0 on 2022-03-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0008_alter_style_maxresolution_alter_style_minresolution'),
    ]

    operations = [
        migrations.AddField(
            model_name='style',
            name='maxzoom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='style',
            name='minzoom',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
