# Generated by Django 4.0 on 2021-12-16 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0008_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='example',
            name='my_column',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
