# Generated by Django 4.0 on 2022-01-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0008_feature_hstore_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='hstore_data',
            new_name='preferences',
        ),
    ]
