# Generated by Django 4.0 on 2022-03-22 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0009_style_maxzoom_style_minzoom'),
    ]

    operations = [
        migrations.RenameField(
            model_name='style',
            old_name='maxResolution',
            new_name='maxScale',
        ),
        migrations.RenameField(
            model_name='style',
            old_name='minResolution',
            new_name='minScale',
        ),
    ]
