# Generated by Django 4.0 on 2021-12-17 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0010_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
    ]
