# Generated by Django 4.0 on 2022-01-08 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0010_feature_jsonb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='preferences',
            new_name='preferences_hstore',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='jsonb',
            new_name='preferences_jsonb',
        ),
    ]
