# Generated by Django 4.0 on 2022-01-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0011_rename_preferences_feature_preferences_hstore_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='preferences_jsonb',
        ),
    ]
