# Generated by Django 4.0 on 2021-12-17 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0012_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='type_geometry',
            field=models.CharField(default=None, max_length=250),
            preserve_default=False,
        ),
    ]
