# Generated by Django 4.0 on 2021-12-17 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0014_alter_feature_type_geometry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='type_geometry',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
