# Generated by Django 4.0 on 2022-01-08 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0015_alter_feature_preferences_jsonb'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='preferences_jsonb',
        ),
    ]
