# Generated by Django 4.0 on 2021-12-17 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0015_alter_feature_type_geometry'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='kvartal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='lesnichestvo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='uch_lesnichestvo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='urochishe',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
