# Generated by Django 4.0 on 2021-12-19 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0016_feature_kvartal_feature_lesnichestvo_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
    ]
