# Generated by Django 4.0 on 2021-12-19 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0018_layer_feature'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='Layer',
        ),
    ]
