# Generated by Django 4.0 on 2022-01-09 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0019_alter_feature_preferences_jsonb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='preferences_hstore',
            new_name='hstore',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='preferences_jsonb',
        ),
    ]
