# Generated by Django 4.0 on 2022-01-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0020_rename_preferences_hstore_feature_hstore_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='jsonb',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
