# Generated by Django 4.0 on 2021-12-19 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0020_layer_feature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
