# Generated by Django 4.0 on 2021-12-19 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0021_alter_feature_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='kvartal',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='lesnichestvo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='uch_lesnichestvo',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='feature',
            name='urochishe',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
