# Generated by Django 4.0 on 2022-01-09 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0021_feature_jsonb'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='hstore',
            new_name='hstore_data',
        ),
        migrations.RenameField(
            model_name='feature',
            old_name='jsonb',
            new_name='jsonb_data',
        ),
    ]
