# Generated by Django 4.0 on 2022-01-09 16:16

from django.db import migrations, models
import geores.models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0036_remove_feature_jsonb_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='jsonb_data',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
