# Generated by Django 4.0 on 2022-01-09 18:17

from django.db import migrations, models
import geores.models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0040_remove_feature_jsonb_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='jsonb_data',
            field=models.JSONField(blank=True, db_index=True, default=geores.models.Feature.net_default, null=True),
        ),
    ]
