# Generated by Django 4.0 on 2022-01-10 07:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0043_alter_feature_jsonb_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='les_name',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='uch_les_name',
        ),
        migrations.RemoveField(
            model_name='feature',
            name='uroch_name',
        ),
    ]
