# Generated by Django 4.0 on 2022-01-11 04:19

import django.contrib.postgres.fields.hstore
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0046_alter_feature_jsonb_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='hstore_data',
            field=django.contrib.postgres.fields.hstore.HStoreField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='feature',
            name='jsonb_data',
            field=models.JSONField(blank=True, db_index=True, default=dict, null=True),
        ),
    ]
