# Generated by Django 4.0 on 2022-01-11 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0048_alter_feature_hstore_data_alter_feature_jsonb_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='jsonb_data',
        ),
    ]
