# Generated by Django 4.0 on 2022-01-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0049_remove_feature_jsonb_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='hstore_data',
            new_name='jsonb_data',
        ),
    ]
