# Generated by Django 4.0 on 2022-01-11 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0052_remove_feature_type_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='jsonb_data',
            field=models.JSONField(blank=True, db_index=True, default=dict, null=True),
        ),
    ]
