# Generated by Django 4.0 on 2022-01-11 13:38

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0053_alter_feature_jsonb_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='forest_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
                ('jsonb_data', models.JSONField(blank=True, db_index=True, default=dict, null=True)),
                ('geom', django.contrib.gis.db.models.fields.GeometryField(srid=4326)),
            ],
        ),
    ]
