# Generated by Django 4.0 on 2022-01-11 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0054_forest_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='jsonb_data',
        ),
        migrations.RemoveField(
            model_name='forest_data',
            name='jsonb_data',
        ),
    ]
