# Generated by Django 4.0 on 2022-01-11 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0055_remove_feature_jsonb_data_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='forest_data',
        ),
    ]
