# Generated by Django 4.0 on 2022-01-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0056_delete_forest_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='jsonb_data',
            field=models.JSONField(blank=True, db_index=True, default=dict, null=True),
        ),
    ]
