# Generated by Django 4.0 on 2022-01-11 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0059_alter_feature_geom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feature',
            name='geom',
        ),
    ]
