# Generated by Django 4.0 on 2022-01-11 21:32

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geores', '0063_alter_feature_jsonb_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='geom',
            field=django.contrib.gis.db.models.fields.GeometryField(null=True, srid=4326),
        ),
    ]
